name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build vuln
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build with CMake
        run: |
          mkdir build
          cd build
          cmake .. -G "Unix Makefiles"
          make

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: vuln-artifact
          path: build/vuln
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    name: Test correct program
    needs: build

    env:
      FNETD_PASSWORD: 1234

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@master
        name: Download build artifacts
        with:
          name: vuln-artifact
          path: build/

      - name: Install fnetd
        run: |
          wget https://cloud.sec.in.tum.de/index.php/s/n5cJnDqnnpSeEpd/download/fnetd.tar.xz -O fnetd.tar.xz
          tar -xf fnetd.tar.xz
          mkdir fnetd/build
          cd fnetd/build
          cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
          make
          cd ../..

      - name: Setup get_flag
        run: gcc tests/get_flag.c -o get_flag -O3

      - uses: JarvusInnovations/background-action@v1
        name: Start fnetd
        with:
          run: |-
            chmod +x build/vuln
            fnetd/build/fnetd -p 1337 -lt 2 -lm 536870912 "strace -f build/vuln" &

          tail: true
          wait-on: tcp:localhost:1337
          wait-for: 1m

      - name: Setup python libs
        run: pip install -r tests/requirements.txt

      - name: Run tests
        run: python -m unittest discover tests/

  test_exploit:
    runs-on: ubuntu-latest
    name: Test exploit
    needs: build

    env:
      FNETD_PASSWORD: 1234
      RELEASE_PORT: 8080
      DEBUG_PORT: 8081

    steps:
      - uses: actions/checkout@v3

      - name: Build Debug
        run: |
          mkdir debug
          cd debug
          cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
          make

      - name: Build Release
        run: |
          mkdir release
          cd release
          cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
          make

      - name: Install fnetd
        run: |
          wget https://cloud.sec.in.tum.de/index.php/s/n5cJnDqnnpSeEpd/download/fnetd.tar.xz -O fnetd.tar.xz
          tar -xf fnetd.tar.xz
          mkdir fnetd/build
          cd fnetd/build
          cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
          make
          cd ../..

      - uses: JarvusInnovations/background-action@v1
        name: Start fnetd debug
        with:
          run: |-
            chmod +x release/vuln
            fnetd/build/fnetd -p $DEBUG_PORT -lt 2 -lm 536870912 "strace -f debug/vuln" &

          tail: true
          wait-on: tcp:localhost:$${{ env.DEBUG_PORT }}
          wait-for: 1m

      - uses: JarvusInnovations/background-action@v1
        name: Start fnetd release
        with:
          run: |-
            chmod +x release/vuln
            fnetd/build/fnetd -p $RELEASE_PORT -lt 2 -lm 536870912 "strace -f release/vuln" &

          tail: true
          wait-on: tcp:localhost:$${{ env.RELEASE_PORT }}
          wait-for: 1m

      - name: Setup python libs
        run: pip install -r tests/requirements.txt

      - name: Run exploit tests
        run: python3 exploit/test_exploit.py -f activation_key.txt
